on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd mailer
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        cd mailer
        python manage.py migrate
    - name: Run tests
      run: |
        cd mailer
        python manage.py test
